
server:
  port: 8080

spring:
   data:
     mongodb:
       uri: mongodb://localhost:27017/test  #mongodb://name:password@localhost:27017/test   \u8D26\u53F7\u5BC6\u7801\u5199\u6CD5
   thymeleaf:
      cache: false
      mode: HTML
      prefix: classpath:/templates/
      suffix: .html
      encoding: utf-8

   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root
      druid:
          initial-size: 1
          min-idle: 1
          max-active: 20
          test-on-borrow: true
          stat-view-servlet:
            allow: true
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocations: classpath:mybatis-config.xml