
server:
  port: 8080

spring:
   thymeleaf:
      cache: false
      mode: HTML
      prefix: classpath:/templates/
      suffix: .html
      encoding: utf-8
#   activemq:  #springboo\u6574\u5408mq
#     broker-url: tcp://127.0.0.1:61616
#     user: admin
#     password: admin
#     in-memory: false  #\u662F\u5426\u542F\u7528\u5185\u5B58\u6A21\u5F0F  \u5C31\u662F\u4E0D\u5B89\u88C5mq  \u9879\u76EE\u542F\u52A8\u540C\u65F6\u4E5F\u542F\u52A8\u4E00\u4E2AMQ\u5B9E\u4F8B   \u5982\u679C\u60F3\u6301\u4E45\u5316\u6D88\u606F \u8BBE\u7F6Efalse
#     packages:
#       trust-all: true  #\u4FE1\u4EFB\u6240\u6709\u7684\u5305   \u5982\u679C\u53D1\u9001\u7684\u662F\u5BF9\u8C61\u6D88\u606F  \u5BF9\u8C61\u5FC5\u987B\u5B9E\u73B0\u5E8F\u5217\u5316
   jms:
     pub-sub-domain: true  #\u5982\u679C\u662F\u70B9\u5BF9\u70B9(queue)\u90A3\u4E48\u6B64\u5904\u9ED8\u8BA4\u662Ffalse  \u5982\u679C\u662F\u53D1\u5E03\u8BA2\u9605(\u5171\u4EAB\u6A21\u5F0F) \u90A3\u4E48\u8BBE\u7F6E\u4E3Atrue

   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root